### ISSUE TITLE
user-auth

### ISSUE THREAD

**Issue by isomdurm** [isomdurm/strida#1]
user-auth: need to complete functionality of the demo button and animation

**Comment by evhumphrey** [comment]
Feedback: 

- [ ] I'm getting a 500 error when trying to sign up
- [ ] Demo doesn't seem to work 
- [ ] Form errors aren't rendered (it seems like anytime you click the submit button, it redirects to `/`)
- [ ] The "Submit" buttons on your forms should be named to "Sign Up" and "Sign In", depending on the form it's in 
- [ ] I would remove the "Sign up with Facebook" and "Sign up with Google" buttons, and I would change "Use my email" to "Sign up for Strida"
- [ ] Styling should be improved, the blue color is a bit intense, and the spacing on your forms looks off
